name: 🐛 错误报告 Bug Report
description: 创建一个 Issue 帮助我们改进组件。
body:
  - type: markdown
    attributes:
      value: |
        **在开始之前……**

        这个表单仅用于错误报告。对于在使用中遇到的问题，请优先使用以下方式寻找解决方案：

        - 查看组件文档 [@nutui/nutui](https://nutui.jd.com/h5/vue/4x/#/zh-CN/guide/intro) [@nutui/nutui-taro](https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/intro)
        - 在 [Issue](https://github.com/jdf2e/nutui/issues) 列表中查找解决方案
        - 查看 [常见问题 QA](https://github.com/jdf2e/nutui/issues/2461)

        注意：如果你发现一个已关闭 issue 的问题在最新版本中仍然存在，请不要在旧 issue 下面留言，而应该当前的表单创建新的 issue。

  - type: dropdown
    id: npm
    attributes:
      label: NutUI 包名
      description: 选择使用的 NutUI 包名
      options:
        - "@nutui/nutui"
        - "@nutui/nutui-taro"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: NutUI 版本号
      description: 输入使用的 NutUI 版本号
      placeholder: 例如：4.0.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 平台
      multiple: true
      description: 选择对应的平台
      options:
        - h5
        - weapp
        - alipay
        - jd
        - tt
        - others

  - type: input
    id: reproduce-link
    attributes:
      label: 重现链接
      description: |
        1、你可以通过 [Playground](https://nutui.jd.com/playground/) 创建一个可复现实例，它基于组件库最新版本的代码。

        2、你可以通过 [CodeSandbox](https://codesandbox.io/s/nutui4-vite-demo-2fw7xh?file=/src/App.vue) 创建一个可复现实例，它支持选择特定版本的 NutUI。

        3、对于 `@nutui/nutui-taro` 中的问题，建议提供一个最小化可复现代码仓库。
        - 最小化：意味着它应该只包含与问题相关的代码与配置，而不是一个庞大的、难以排查问题的仓库。
        - 可复现：这是创建 issue 的基础要求。

        请不要乱填一个链接，那只会让你的 issue 被直接关闭。
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
