name: CI

on:
  push:
    branches:
      - vitest

  pull_request:
    branches:
      - vitest

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: corepack enable

    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run test cases
      run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: corepack enable

    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: ppm build

    - name: Build Taro
      run: ppm build:taro:vue